let obj = {
    '918': ['Babilon-M', './img/babilon-m.png'],
    '98': ['Babilon-M', './img/babilon-m.png'],
    '94': ['Babilon-M', './img/babilon-m.png'],
    '00': ['Megafon', './img/megafon.jpg'],
    '36': ['Megafon', './img/megafon.jpg'],
    '55': ['Megafon', './img/megafon.jpg'],
    '88': ['Megafon', './img/megafon.jpg'],
    '90': ['Megafon', './img/megafon.jpg'],
    '40': ['Zet Mobile','./img/zetmobile.png'],
    '80': ['Zet Mobile','./img/zetmobile.png'],
    '91': ['Zet Mobile','./img/zetmobile.png'],
    '50': ['Tcell', './img/tcell.png'],
    '70': ['Tcell', './img/tcell.png'],
    '77': ['Tcell', './img/tcell.png'],
    '93': ['Tcell', './img/tcell.png'],
    '99': ['Tcell', './img/tcell.png'],
    '92': ['Tcell', './img/tcell.png'],
    '1111': ['Tcell', './img/tcell.png'],
    '1122': ['Tcell', './img/tcell.png'],
    '1133': ['Tcell', './img/tcell.png'],
    '1144': ['Tcell', './img/tcell.png'],
    '1155': ['Tcell', './img/tcell.png'],
    '1166': ['Tcell', './img/tcell.png'],
    '1177': ['Tcell', './img/tcell.png'],
    '1188': ['Tcell', './img/tcell.png'],
    '1199': ['Tcell', './img/tcell.png'],
    '1': ['O Mobile', './img/omobile.jpg'],
    '10': ['O Mobile', './img/omobile.jpg'],
    '2': ['O Mobile', './img/omobile.jpg'],
    '20': ['O Mobile', './img/omobile.jpg'],
    '30': ['O Mobile', './img/omobile.jpg'],
    '44': ['Babilon-T', './img/babilon-m.png'],
    '37370': ['TajikTelecom', './img/tajiktelecom.png'],
    '37371': ['TajikTelecom', './img/tajiktelecom.png'],
    '37372': ['TajikTelecom', './img/tajiktelecom.png'],
    '37376': ['TajikTelecom', './img/tajiktelecom.png'],
    '37379': ['TajikTelecom', './img/tajiktelecom.png'],
    '83794[5': ['TajikTelecom', './img/tajiktelecom.png'],
    '37374': ['TajikTelecom', './img/tajiktelecom.png'],
    '1919': ['TajikTelecom', './img/tajiktelecom.png'],
    '37375': ['TajikTelecom', './img/tajiktelecom.png'],
    '37377': ['TajikTelecom', './img/tajiktelecom.png'],
    '37378': ['TajikTelecom', './img/tajiktelecom.png'],
    '37373': ['TajikTelecom', './img/tajiktelecom.png'],
    '83130': ['TajikTelecom', './img/tajiktelecom.png'],
    '83131': ['TajikTelecom', './img/tajiktelecom.png'],
    '83132': ['TajikTelecom', './img/tajiktelecom.png'],
    '83133': ['TajikTelecom', './img/tajiktelecom.png'],
    '83134': ['TajikTelecom', './img/tajiktelecom.png'],
    '83135': ['TajikTelecom', './img/tajiktelecom.png'],
    '83136': ['TajikTelecom', './img/tajiktelecom.png'],
    '83137': ['TajikTelecom', './img/tajiktelecom.png'],
    '83138': ['TajikTelecom', './img/tajiktelecom.png'],
    '83139': ['TajikTelecom', './img/tajiktelecom.png'],
    '83141': ['TajikTelecom', './img/tajiktelecom.png'],
    '83153': ['TajikTelecom', './img/tajiktelecom.png'],
    '83154': ['TajikTelecom', './img/tajiktelecom.png'],
    '83155': ['TajikTelecom', './img/tajiktelecom.png'],
    '83156': ['TajikTelecom', './img/tajiktelecom.png'],
    '831565': ['TajikTelecom', './img/tajiktelecom.png'],
    '83222': ['TajikTelecom', './img/tajiktelecom.png'],
    '83240': ['TajikTelecom', './img/tajiktelecom.png'],
    '83242': ['TajikTelecom', './img/tajiktelecom.png'],
    '83243': ['TajikTelecom', './img/tajiktelecom.png'],
    '83245': ['TajikTelecom', './img/tajiktelecom.png'],
    '83246': ['TajikTelecom', './img/tajiktelecom.png'],
    '83247': ['TajikTelecom', './img/tajiktelecom.png'],
    '83248': ['TajikTelecom', './img/tajiktelecom.png'],
    '83249': ['TajikTelecom', './img/tajiktelecom.png'],
    '83250': ['TajikTelecom', './img/tajiktelecom.png'],
    '83251': ['TajikTelecom', './img/tajiktelecom.png'],
    '83252': ['TajikTelecom', './img/tajiktelecom.png'],
    '83258': ['TajikTelecom', './img/tajiktelecom.png'],
    '83311': ['TajikTelecom', './img/tajiktelecom.png'],
    '83312': ['TajikTelecom', './img/tajiktelecom.png'],
    '83314': ['TajikTelecom', './img/tajiktelecom.png'],
    '83315': ['TajikTelecom', './img/tajiktelecom.png'],
    '83316': ['TajikTelecom', './img/tajiktelecom.png'],
    '83317': ['TajikTelecom', './img/tajiktelecom.png'],
    '83318': ['TajikTelecom', './img/tajiktelecom.png'],
    '83319': ['TajikTelecom', './img/tajiktelecom.png'],
    '83322': ['TajikTelecom', './img/tajiktelecom.png'],
    '83357': ['TajikTelecom', './img/tajiktelecom.png'],
    '83358': ['TajikTelecom', './img/tajiktelecom.png'],
    '83422': ['TajikTelecom', './img/tajiktelecom.png'],
    '83441': ['TajikTelecom', './img/tajiktelecom.png'],
    '83442': ['TajikTelecom', './img/tajiktelecom.png'],
    '83443': ['TajikTelecom', './img/tajiktelecom.png'],
    '83445': ['TajikTelecom', './img/tajiktelecom.png'],
    '83451': ['TajikTelecom', './img/tajiktelecom.png'],
    '83452': ['TajikTelecom', './img/tajiktelecom.png'],
    '83453': ['TajikTelecom', './img/tajiktelecom.png'],
    '83454': ['TajikTelecom', './img/tajiktelecom.png'],
    '83455': ['TajikTelecom', './img/tajiktelecom.png'],
    '83456': ['TajikTelecom', './img/tajiktelecom.png'],
    '83458': ['TajikTelecom', './img/tajiktelecom.png'],
    '83462': ['TajikTelecom', './img/tajiktelecom.png'],
    '83464': ['TajikTelecom', './img/tajiktelecom.png'],
    '83465': ['TajikTelecom', './img/tajiktelecom.png'],
    '83467': ['TajikTelecom', './img/tajiktelecom.png'],
    '83475': ['TajikTelecom', './img/tajiktelecom.png'],
    '83479': ['TajikTelecom', './img/tajiktelecom.png'],
    '83480': ['TajikTelecom', './img/tajiktelecom.png'],
    '83522': ['TajikTelecom', './img/tajiktelecom.png'],
    '83551': ['TajikTelecom', './img/tajiktelecom.png'],
    '83552': ['TajikTelecom', './img/tajiktelecom.png'],
    '8355215': ['TajikTelecom', './img/tajiktelecom.png'],
    '83553': ['TajikTelecom', './img/tajiktelecom.png'],
    '83554': ['TajikTelecom', './img/tajiktelecom.png'],
    '83555': ['TajikTelecom', './img/tajiktelecom.png'],
    '83556': ['TajikTelecom', './img/tajiktelecom.png'],
}

let paymentNumberButton = document.querySelectorAll('.payment__number');

function getOperator() {
    for (const key in obj) {
        if (field.value === key) {
            operatorTitle.textContent = obj[key][0];
            operatorPct.src = obj[key][1];
        }
    }
}

field.addEventListener('input', () => getOperator());

for (const btn of paymentNumberButton) {
    btn.addEventListener('click', () => getOperator());
}